/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AllRank: typeof import('./src/components/AllRank.vue')['default']
    AsideMenu: typeof import('./src/components/AsideMenu.vue')['default']
    CoreBlock: typeof import('./src/components/CoreBlock.vue')['default']
    HeaderBlock: typeof import('./src/components/HeaderBlock.vue')['default']
    LineChart: typeof import('./src/components/LineChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StockIndex: typeof import('./src/components/StockIndex.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
